import { NextRequest, NextResponse } from 'next/server';
import { connectDB } from '@/lib/mongodb';
import { getSession } from '@/lib/auth';
import Client from '@/models/Client';
import Board from '@/models/Board';
import Task from '@/models/Task';

const MONTH_NAMES = ['January','February','March','April','May','June','July','August','September','October','November','December'];

function daysAgo(n: number): Date {
  return new Date(Date.now() - n * 86_400_000);
}

function hoursAgo(n: number): Date {
  return new Date(Date.now() - n * 3_600_000);
}

export async function POST(request: NextRequest) {
  const session = await getSession();
  if (!session || session.role !== 'CEO') {
    return NextResponse.json({ error: 'CEO only' }, { status: 403 });
  }

  await connectDB();

  // Duplicate protection
  const existing = await Client.findOne({ isDemo: true });
  if (existing) {
    return NextResponse.json({ error: 'Demo report data already exists. Use Reset Demo Data to start fresh.' }, { status: 409 });
  }

  const body = await request.json().catch(() => ({}));
  const now = new Date();
  const month: number = body.month ?? now.getMonth() + 1;
  const year: number = body.year ?? now.getFullYear();
  const monthName = MONTH_NAMES[month - 1];
  const createdBy = session.userId;

  // ─── Client 1: Timimetal ────────────────────────────────────────────────
  const timimetal = await Client.create({
    name: 'Timimetal',
    businessType: 'Manufacturing',
    status: 'ACTIVE',
    instagramUrl: 'https://instagram.com/timimetal',
    isDemo: true,
  });

  const timimetalBoard = await Board.create({
    clientId: timimetal._id,
    title: `Timimetal — ${monthName} ${year}`,
    month,
    year,
    status: 'ACTIVE',
    createdBy,
    isDemo: true,
    autoGeneratedTasksCount: 6,
  });

  const timimetalTasks = [
    // Post 1 — completed
    {
      title: 'Summer Collection Photo Post',
      contentType: 'POST',
      platforms: ['Instagram'],
      postedDate: daysAgo(10),
      reporting: {
        reportDueAt: hoursAgo(10 * 24 - 48),
        reportStatus: 'COMPLETED',
        reportCompletedAt: daysAgo(8),
        metrics: {
          views: 8420, reach: 6300, likes: 524, comments: 67, shares: 112, saves: 203,
          profileVisits: 89, linkClicks: 34, engagementRate: 14.38,
          notes: 'Strong engagement on summer theme. Best performing post this month.',
        },
      },
    },
    // Post 2 — completed
    {
      title: 'Product Showcase',
      contentType: 'POST',
      platforms: ['Instagram'],
      postedDate: daysAgo(8),
      reporting: {
        reportDueAt: hoursAgo(8 * 24 - 48),
        reportStatus: 'COMPLETED',
        reportCompletedAt: daysAgo(6),
        metrics: {
          views: 5890, reach: 4200, likes: 310, comments: 42, shares: 78, saves: 145,
          profileVisits: 56, linkClicks: 22, engagementRate: 13.69,
          notes: 'Good reach, steady engagement on product content.',
        },
      },
    },
    // Reel 1 — completed
    {
      title: 'Behind the Scenes Reel',
      contentType: 'REEL',
      platforms: ['Instagram'],
      postedDate: daysAgo(6),
      reporting: {
        reportDueAt: hoursAgo(6 * 24 - 48),
        reportStatus: 'COMPLETED',
        reportCompletedAt: daysAgo(4),
        metrics: {
          views: 15600, reach: 12400, likes: 892, comments: 134, shares: 267, saves: 445,
          profileVisits: 178, linkClicks: 67, engagementRate: 14.02,
          notes: 'Reels consistently outperform static posts. BTS content resonates well.',
        },
      },
    },
    // Story 1 — completed
    {
      title: 'Daily Flash Sale Story',
      contentType: 'STORY',
      platforms: ['Instagram'],
      postedDate: daysAgo(5),
      reporting: {
        reportDueAt: hoursAgo(5 * 24 - 24),
        reportStatus: 'COMPLETED',
        reportCompletedAt: daysAgo(4),
        metrics: {
          views: 3200, reach: 2900, storyReplies: 45, storyTapsForward: 234,
          storyTapsBack: 56, storyExits: 89, linkClicks: 123,
          notes: 'Flash sale story drove high link clicks. Audience engaged well.',
        },
      },
    },
    // Story 2 — missing
    {
      title: 'Product Highlight Story',
      contentType: 'STORY',
      platforms: ['Instagram'],
      postedDate: daysAgo(3),
      reporting: {
        reportDueAt: hoursAgo(3 * 24 - 24),
        reportStatus: 'NEEDS_REPORT_DATA',
      },
    },
    // Post 3 — missing
    {
      title: 'Client Testimonial Post',
      contentType: 'POST',
      platforms: ['Instagram'],
      postedDate: daysAgo(2),
      reporting: {
        reportDueAt: hoursAgo(2 * 24 - 48),
        reportStatus: 'NEEDS_REPORT_DATA',
      },
    },
  ];

  await Task.insertMany(timimetalTasks.map(t => ({
    ...t,
    boardId: timimetalBoard._id,
    clientId: timimetal._id,
    status: 'POSTED',
    priority: 'MEDIUM',
    createdBy,
    isDemo: true,
    isOpenForClaim: false,
    autoGenerated: true,
  })));

  // ─── Client 2: Meda 3 ───────────────────────────────────────────────────
  const meda3 = await Client.create({
    name: 'Meda 3',
    businessType: 'Retail',
    status: 'ACTIVE',
    instagramUrl: 'https://instagram.com/meda3',
    isDemo: true,
  });

  const meda3Board = await Board.create({
    clientId: meda3._id,
    title: `Meda 3 — ${monthName} ${year}`,
    month,
    year,
    status: 'ACTIVE',
    createdBy,
    isDemo: true,
    autoGeneratedTasksCount: 3,
  });

  const meda3Tasks = [
    // Post 1 — completed
    {
      title: 'Brand Launch Post',
      contentType: 'POST',
      platforms: ['Instagram', 'Facebook'],
      postedDate: daysAgo(9),
      reporting: {
        reportDueAt: hoursAgo(9 * 24 - 48),
        reportStatus: 'COMPLETED',
        reportCompletedAt: daysAgo(7),
        metrics: {
          views: 12300, reach: 9800, likes: 745, comments: 98, shares: 189, saves: 312,
          profileVisits: 145, linkClicks: 78, engagementRate: 13.71,
          notes: 'Launch post performed very well across both platforms.',
        },
      },
    },
    // Reel 1 — completed
    {
      title: 'Product Demo Reel',
      contentType: 'REEL',
      platforms: ['Instagram'],
      postedDate: daysAgo(5),
      reporting: {
        reportDueAt: hoursAgo(5 * 24 - 48),
        reportStatus: 'COMPLETED',
        reportCompletedAt: daysAgo(3),
        metrics: {
          views: 22400, reach: 18600, likes: 1234, comments: 189, shares: 423, saves: 678,
          profileVisits: 267, linkClicks: 145, engagementRate: 13.57,
          notes: 'Product demo reel exceeded expectations. Viral reach boost from shares.',
        },
      },
    },
    // Story 1 — missing
    {
      title: 'Flash Sale Story',
      contentType: 'STORY',
      platforms: ['Instagram'],
      postedDate: daysAgo(2),
      reporting: {
        reportDueAt: hoursAgo(2 * 24 - 24),
        reportStatus: 'NEEDS_REPORT_DATA',
      },
    },
  ];

  await Task.insertMany(meda3Tasks.map(t => ({
    ...t,
    boardId: meda3Board._id,
    clientId: meda3._id,
    status: 'POSTED',
    priority: 'MEDIUM',
    createdBy,
    isDemo: true,
    isOpenForClaim: false,
    autoGenerated: true,
  })));

  return NextResponse.json({
    message: 'Demo data created successfully',
    data: {
      clients: 2,
      boards: 2,
      tasks: timimetalTasks.length + meda3Tasks.length,
      month: monthName,
      year,
    },
  });
}

export async function DELETE(_request: NextRequest) {
  const session = await getSession();
  if (!session || session.role !== 'CEO') {
    return NextResponse.json({ error: 'CEO only' }, { status: 403 });
  }

  await connectDB();

  const [clients, boards, tasks] = await Promise.all([
    Client.deleteMany({ isDemo: true }),
    Board.deleteMany({ isDemo: true }),
    Task.deleteMany({ isDemo: true }),
  ]);

  return NextResponse.json({
    message: 'Demo data reset successfully',
    data: {
      clientsDeleted: clients.deletedCount,
      boardsDeleted: boards.deletedCount,
      tasksDeleted: tasks.deletedCount,
    },
  });
}
