/**
 * DB-backed board import — creates the Board plus one Task per validated
 * content item, reusing the same checklist templates and field conventions
 * as manual board creation (see '@/lib/generateMonthlyContentCards') so
 * imported cards behave identically to natively-created ones.
 */
import { connectDB } from '@/lib/mongodb';
import Client from '@/models/Client';
import Board from '@/models/Board';
import Task from '@/models/Task';
import ActivityLog from '@/models/ActivityLog';
import { POST_CHECKLIST, REEL_CHECKLIST, STORY_CHECKLIST, toChecklist } from '@/lib/generateMonthlyContentCards';
import type { NormalizedContentItem, BoardImportContentType } from '@/lib/boardImport';

export class BoardImportError extends Error {
  status: number;
  constructor(message: string, status = 400) {
    super(message);
    this.status = status;
    this.name = 'BoardImportError';
  }
}

function checklistFor(contentType: BoardImportContentType): { text: string; done: boolean }[] {
  if (contentType === 'POST') return toChecklist(POST_CHECKLIST);
  if (contentType === 'REEL') return toChecklist(REEL_CHECKLIST);
  if (contentType === 'STORY') return toChecklist(STORY_CHECKLIST);
  return [];
}

export interface ConfirmBoardImportInput {
  clientId: string;
  boardName: string;
  month: number;
  year: number;
  items: NormalizedContentItem[];
  createdBy: string;
  confirmDuplicate?: boolean;
}

export async function createBoardFromImport(input: ConfirmBoardImportInput) {
  await connectDB();

  const client = await Client.findById(input.clientId);
  if (!client) throw new BoardImportError('Client not found', 404);
  if (!input.boardName?.trim()) throw new BoardImportError('Board name is required');
  if (!input.month || input.month < 1 || input.month > 12) throw new BoardImportError('Invalid month');
  if (!input.year) throw new BoardImportError('Invalid year');

  const existing = await Board.findOne({ clientId: client._id, month: input.month, year: input.year });
  if (existing && !input.confirmDuplicate) {
    throw new BoardImportError(
      `A board for this client already exists for ${new Date(input.year, input.month - 1).toLocaleString('en-US', { month: 'long' })} ${input.year}.`,
      409
    );
  }

  const board = await Board.create({
    clientId: client._id,
    title: input.boardName.trim(),
    month: input.month,
    year: input.year,
    status: 'ACTIVE',
    createdBy: input.createdBy,
  });

  const taskDocs = input.items.map((item) => ({
    boardId: board._id,
    clientId: client._id,
    title: item.title,
    description: [item.description, item.notes].filter(Boolean).join('\n\n') || undefined,
    contentType: item.contentType,
    status: 'CONTENT_PREPARATION' as const,
    priority: 'MEDIUM' as const,
    platforms: item.platforms,
    scheduledDate: new Date(item.scheduledDate),
    checklist: checklistFor(item.contentType),
    isOpenForClaim: true,
    autoGenerated: true,
    createdBy: input.createdBy,
  }));

  const tasks = taskDocs.length > 0 ? await Task.insertMany(taskDocs) : [];

  await Board.findByIdAndUpdate(board._id, { autoGeneratedTasksCount: tasks.length, generatedAt: new Date() });

  await ActivityLog.create({
    userId: input.createdBy,
    action: 'IMPORT',
    entityType: 'Board',
    entityId: board._id,
    message: `Imported ${tasks.length} content item(s) into board "${board.title}" for "${client.name}"`,
  });

  const populated = await Board.findById(board._id).populate('clientId', 'name status');
  return { board: populated, taskCount: tasks.length };
}
