import mongoose from 'mongoose';
import Task from '@/models/Task';

export type DeadlinePattern = 'NONE' | 'SPREAD' | 'SAME';

export interface GenerateContentCardsOptions {
  boardId: string;
  clientId: string;
  month: number;
  year: number;
  numberOfPosts: number;
  numberOfReels: number;
  numberOfStories: number;
  platforms: string[];
  defaultAssignedWorker?: string;
  isOpenForClaim: boolean;
  deadlinePattern: DeadlinePattern;
  sameDeadline?: string;
  createdBy: string;
}

const POST_CHECKLIST = [
  'Content idea prepared',
  'Photos/videos selected',
  'Design created',
  'Caption written',
  'Hashtags added',
  'Sent to Quality Assurance',
  'Quality checked',
  'Client approval received (if needed)',
  'Ready to post',
  'Posted',
];

const REEL_CHECKLIST = [
  'Video selected',
  'Clips organized',
  'Reel edited',
  'Music/sound selected',
  'Captions/subtitles added',
  'Cover selected',
  'Caption written',
  'Sent to Quality Assurance',
  'Quality checked',
  'Client approval received (if needed)',
  'Ready to post',
  'Posted',
];

const STORY_CHECKLIST = [
  'Story idea prepared',
  'Photo/video selected',
  'Story design/edit created',
  'Text/sticker added (if needed)',
  'Sent to Quality Assurance',
  'Quality checked',
  'Ready to post',
  'Posted',
];

function toChecklist(items: string[]) {
  return items.map(text => ({ text, done: false }));
}

function getDaysInMonth(month: number, year: number): number {
  return new Date(year, month, 0).getDate();
}

function spreadDates(month: number, year: number, count: number): (Date | undefined)[] {
  if (count === 0) return [];
  const daysInMonth = getDaysInMonth(month, year);
  if (count === 1) {
    return [new Date(year, month - 1, Math.floor(daysInMonth / 2))];
  }
  const firstDay = 3;
  const lastDay = daysInMonth - 3;
  const spacing = (lastDay - firstDay) / (count - 1);
  return Array.from({ length: count }, (_, i) => {
    const day = Math.round(firstDay + spacing * i);
    return new Date(year, month - 1, day);
  });
}

export async function generateMonthlyContentCards(opts: GenerateContentCardsOptions) {
  const {
    boardId, clientId, month, year,
    numberOfPosts, numberOfReels, numberOfStories,
    platforms, defaultAssignedWorker, isOpenForClaim,
    deadlinePattern, sameDeadline, createdBy,
  } = opts;

  const boardObjId  = new mongoose.Types.ObjectId(boardId);
  const clientObjId = new mongoose.Types.ObjectId(clientId);
  const createdByObjId = new mongoose.Types.ObjectId(createdBy);
  const assignedToObjId = defaultAssignedWorker ? new mongoose.Types.ObjectId(defaultAssignedWorker) : undefined;
  const sameDeadlineDate = deadlinePattern === 'SAME' && sameDeadline ? new Date(sameDeadline) : undefined;

  const postDates  = deadlinePattern === 'SPREAD' ? spreadDates(month, year, numberOfPosts) : Array<Date | undefined>(numberOfPosts).fill(sameDeadlineDate);
  const reelDates  = deadlinePattern === 'SPREAD' ? spreadDates(month, year, numberOfReels) : Array<Date | undefined>(numberOfReels).fill(sameDeadlineDate);
  const storyDates = deadlinePattern === 'SPREAD' ? spreadDates(month, year, numberOfStories) : Array<Date | undefined>(numberOfStories).fill(sameDeadlineDate);

  const base = {
    boardId: boardObjId,
    clientId: clientObjId,
    status: 'CONTENT_PREPARATION',
    priority: 'MEDIUM',
    platforms,
    isOpenForClaim,
    autoGenerated: true,
    createdBy: createdByObjId,
    ...(assignedToObjId ? { assignedTo: assignedToObjId } : {}),
  };

  const cards: object[] = [];

  for (let i = 0; i < numberOfPosts; i++) {
    cards.push({
      ...base,
      title: `Post ${i + 1}`,
      contentType: 'POST',
      scheduledDate: postDates[i] ?? undefined,
      checklist: toChecklist(POST_CHECKLIST),
    });
  }

  for (let i = 0; i < numberOfReels; i++) {
    cards.push({
      ...base,
      title: `Reel ${i + 1}`,
      contentType: 'REEL',
      scheduledDate: reelDates[i] ?? undefined,
      checklist: toChecklist(REEL_CHECKLIST),
    });
  }

  for (let i = 0; i < numberOfStories; i++) {
    cards.push({
      ...base,
      title: `Story ${i + 1}`,
      contentType: 'STORY',
      scheduledDate: storyDates[i] ?? undefined,
      checklist: toChecklist(STORY_CHECKLIST),
    });
  }

  const inserted = cards.length > 0 ? await Task.insertMany(cards) : [];
  return { cards: inserted, cardCount: inserted.length };
}
