import mongoose from 'mongoose';
import Task from '@/models/Task';
import ContentItem from '@/models/ContentItem';

export type DeadlinePattern = 'NONE' | 'SPREAD' | 'SAME';

export interface GenerateOptions {
  boardId: string;
  clientId: string;
  month: number;
  year: number;
  numberOfPosts: number;
  numberOfReels: number;
  numberOfStories: number;
  numberOfPhotoshoots: number;
  numberOfVideoShoots: number;
  numberOfDroneShoots: number;
  platforms: string[];
  defaultAssignedWorker?: string;
  isOpenForClaim: boolean;
  deadlinePattern: DeadlinePattern;
  sameDeadline?: string;
  createdBy: string;
}

function getDaysInMonth(month: number, year: number): number {
  return new Date(year, month, 0).getDate();
}

function spreadDates(month: number, year: number, count: number): (Date | undefined)[] {
  if (count === 0) return [];
  const daysInMonth = getDaysInMonth(month, year);
  if (count === 1) {
    return [new Date(year, month - 1, Math.floor(daysInMonth / 2))];
  }
  const firstDay = 3;
  const lastDay = daysInMonth - 3;
  const spacing = (lastDay - firstDay) / (count - 1);
  return Array.from({ length: count }, (_, i) => {
    const day = Math.round(firstDay + spacing * i);
    return new Date(year, month - 1, day);
  });
}

function addDays(date: Date, days: number): Date {
  const d = new Date(date);
  d.setDate(d.getDate() + days);
  return d;
}

export async function generateMonthlyBoardTasks(opts: GenerateOptions) {
  const {
    boardId, clientId, month, year,
    numberOfPosts, numberOfReels, numberOfStories,
    numberOfPhotoshoots, numberOfVideoShoots, numberOfDroneShoots,
    platforms, defaultAssignedWorker, isOpenForClaim,
    deadlinePattern, sameDeadline, createdBy,
  } = opts;

  const boardObjId = new mongoose.Types.ObjectId(boardId);
  const clientObjId = new mongoose.Types.ObjectId(clientId);
  const createdByObjId = new mongoose.Types.ObjectId(createdBy);
  const assignedToObjId = defaultAssignedWorker ? new mongoose.Types.ObjectId(defaultAssignedWorker) : undefined;
  const sameDeadlineDate = deadlinePattern === 'SAME' && sameDeadline ? new Date(sameDeadline) : undefined;

  const postDates = deadlinePattern === 'SPREAD' ? spreadDates(month, year, numberOfPosts) : Array(numberOfPosts).fill(sameDeadlineDate);
  const reelDates = deadlinePattern === 'SPREAD' ? spreadDates(month, year, numberOfReels) : Array(numberOfReels).fill(sameDeadlineDate);
  const storyDates = deadlinePattern === 'SPREAD' ? spreadDates(month, year, numberOfStories) : Array(numberOfStories).fill(sameDeadlineDate);

  const taskDocs: object[] = [];
  const contentItemDocs: object[] = [];

  // POST content items
  const postItemIds: mongoose.Types.ObjectId[] = [];
  for (let i = 0; i < numberOfPosts; i++) {
    const id = new mongoose.Types.ObjectId();
    postItemIds.push(id);
    contentItemDocs.push({
      _id: id,
      clientId: clientObjId,
      boardId: boardObjId,
      title: `Post ${i + 1}`,
      contentType: 'POST',
      status: 'IDEA',
      platforms,
      scheduledDate: postDates[i] ?? undefined,
      createdBy: createdByObjId,
    });
  }

  // REEL content items
  const reelItemIds: mongoose.Types.ObjectId[] = [];
  for (let i = 0; i < numberOfReels; i++) {
    const id = new mongoose.Types.ObjectId();
    reelItemIds.push(id);
    contentItemDocs.push({
      _id: id,
      clientId: clientObjId,
      boardId: boardObjId,
      title: `Reel ${i + 1}`,
      contentType: 'REEL',
      status: 'IDEA',
      platforms,
      scheduledDate: reelDates[i] ?? undefined,
      createdBy: createdByObjId,
    });
  }

  // STORY content items
  const storyItemIds: mongoose.Types.ObjectId[] = [];
  for (let i = 0; i < numberOfStories; i++) {
    const id = new mongoose.Types.ObjectId();
    storyItemIds.push(id);
    contentItemDocs.push({
      _id: id,
      clientId: clientObjId,
      boardId: boardObjId,
      title: `Story ${i + 1}`,
      contentType: 'STORY',
      status: 'IDEA',
      platforms,
      scheduledDate: storyDates[i] ?? undefined,
      createdBy: createdByObjId,
    });
  }

  const baseTaskFields = {
    boardId: boardObjId,
    clientId: clientObjId,
    status: 'TO_DO',
    priority: 'MEDIUM',
    platforms,
    isOpenForClaim,
    ...(assignedToObjId ? { assignedTo: assignedToObjId } : {}),
    createdBy: createdByObjId,
    autoGenerated: true,
  };

  // POST tasks
  for (let i = 0; i < numberOfPosts; i++) {
    const postingDate = postDates[i] as Date | undefined;
    const reportDate = postingDate ? addDays(postingDate, 3) : undefined;
    const group = `POST_${i + 1}`;
    const base = { ...baseTaskFields, contentItemId: postItemIds[i], generationGroup: group };

    taskDocs.push(
      { ...base, title: `Post ${i + 1} — Concept & Copywriting`, taskType: 'COPYWRITING', deadline: postingDate },
      { ...base, title: `Post ${i + 1} — Design/Edit`, taskType: 'POST_DESIGN', deadline: postingDate },
      { ...base, title: `Post ${i + 1} — Client Approval`, taskType: 'CLIENT_APPROVAL', deadline: postingDate },
      { ...base, title: `Post ${i + 1} — Posting`, taskType: 'POSTING', deadline: postingDate },
      { ...base, title: `Post ${i + 1} — Report after 3 days`, taskType: 'REPORTING', deadline: reportDate },
    );
  }

  // REEL tasks
  for (let i = 0; i < numberOfReels; i++) {
    const postingDate = reelDates[i] as Date | undefined;
    const reportDate = postingDate ? addDays(postingDate, 3) : undefined;
    const group = `REEL_${i + 1}`;
    const base = { ...baseTaskFields, contentItemId: reelItemIds[i], generationGroup: group };

    taskDocs.push(
      { ...base, title: `Reel ${i + 1} — Video Editing`, taskType: 'EDITING', deadline: postingDate },
      { ...base, title: `Reel ${i + 1} — Caption & Hashtags`, taskType: 'COPYWRITING', deadline: postingDate },
      { ...base, title: `Reel ${i + 1} — Client Approval`, taskType: 'CLIENT_APPROVAL', deadline: postingDate },
      { ...base, title: `Reel ${i + 1} — Posting`, taskType: 'POSTING', deadline: postingDate },
      { ...base, title: `Reel ${i + 1} — Report after 3 days`, taskType: 'REPORTING', deadline: reportDate },
    );
  }

  // STORY tasks
  for (let i = 0; i < numberOfStories; i++) {
    const postingDate = storyDates[i] as Date | undefined;
    const group = `STORY_${i + 1}`;
    const base = { ...baseTaskFields, contentItemId: storyItemIds[i], generationGroup: group };

    taskDocs.push(
      { ...base, title: `Story ${i + 1} — Design/Edit`, taskType: 'POST_DESIGN', deadline: postingDate },
      { ...base, title: `Story ${i + 1} — Posting`, taskType: 'POSTING', deadline: postingDate },
    );
  }

  // PHOTOSHOOT tasks
  for (let i = 0; i < numberOfPhotoshoots; i++) {
    const label = numberOfPhotoshoots === 1 ? 'Monthly Photoshoot' : `Photoshoot ${i + 1}`;
    taskDocs.push({
      ...baseTaskFields,
      title: label,
      taskType: 'PHOTOSHOOT',
      generationGroup: `PHOTOSHOOT_${i + 1}`,
      deadline: deadlinePattern === 'SAME' ? sameDeadlineDate : undefined,
    });
  }

  // VIDEO SHOOT tasks
  for (let i = 0; i < numberOfVideoShoots; i++) {
    const label = numberOfVideoShoots === 1 ? 'Monthly Video Shoot' : `Video Shoot ${i + 1}`;
    taskDocs.push({
      ...baseTaskFields,
      title: label,
      taskType: 'VIDEO_SHOOT',
      generationGroup: `VIDEO_SHOOT_${i + 1}`,
      deadline: deadlinePattern === 'SAME' ? sameDeadlineDate : undefined,
    });
  }

  // DRONE SHOOT tasks
  for (let i = 0; i < numberOfDroneShoots; i++) {
    const label = numberOfDroneShoots === 1 ? 'Monthly Drone Shoot' : `Drone Shoot ${i + 1}`;
    taskDocs.push({
      ...baseTaskFields,
      title: label,
      taskType: 'DRONE',
      generationGroup: `DRONE_SHOOT_${i + 1}`,
      deadline: deadlinePattern === 'SAME' ? sameDeadlineDate : undefined,
    });
  }

  const [contentItems, tasks] = await Promise.all([
    contentItemDocs.length > 0 ? ContentItem.insertMany(contentItemDocs) : Promise.resolve([]),
    taskDocs.length > 0 ? Task.insertMany(taskDocs) : Promise.resolve([]),
  ]);

  return { tasks, contentItems, taskCount: tasks.length };
}
