'use client';

import { useState, useEffect, use } from 'react';
import Topbar from '@/components/layout/Topbar';
import Button from '@/components/ui/Button';
import { PriorityBadge, PlatformBadge } from '@/components/ui/Badge';
import Modal from '@/components/ui/Modal';
import { Input, Select, Textarea } from '@/components/ui/Input';
import LoadingSpinner from '@/components/ui/LoadingSpinner';
import { formatDate, isOverdue, TASK_TYPES, PLATFORMS } from '@/lib/utils';
import type { IBoard, ITask, IClient, IUser, TaskStatus, TaskPriority, TaskType } from '@/types';
import { Plus, ArrowLeft, AlertCircle, CheckSquare, Zap, Camera, Video, Image, FileText } from 'lucide-react';
import Link from 'next/link';
import toast from 'react-hot-toast';

const STATUSES: { key: TaskStatus; label: string; color: string }[] = [
  { key: 'TO_DO', label: 'To Do', color: '#6b7280' },
  { key: 'IN_PROGRESS', label: 'In Progress', color: '#3b82f6' },
  { key: 'WAITING_APPROVAL', label: 'Waiting Approval', color: '#f59e0b' },
  { key: 'APPROVED', label: 'Approved', color: '#10b981' },
  { key: 'SCHEDULED', label: 'Scheduled', color: '#8b5cf6' },
  { key: 'POSTED', label: 'Posted', color: '#34d399' },
  { key: 'DONE', label: 'Done', color: '#22c55e' },
];

const emptyTask = { title: '', description: '', taskType: 'OTHER' as TaskType, priority: 'MEDIUM' as TaskPriority, assignedTo: '', deadline: '', platforms: [] as string[], isOpenForClaim: false, checklist: '' };

export default function BoardDetailContent({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const [board, setBoard] = useState<IBoard | null>(null);
  const [tasks, setTasks] = useState<ITask[]>([]);
  const [workers, setWorkers] = useState<IUser[]>([]);
  const [loading, setLoading] = useState(true);
  const [showTaskForm, setShowTaskForm] = useState(false);
  const [taskForm, setTaskForm] = useState(emptyTask);
  const [saving, setSaving] = useState(false);
  const [selectedPlatforms, setSelectedPlatforms] = useState<string[]>([]);
  const [updatingTask, setUpdatingTask] = useState<string | null>(null);

  useEffect(() => {
    async function load() {
      setLoading(true);
      const [boardRes, workersRes] = await Promise.all([
        fetch(`/api/boards/${id}`),
        fetch('/api/users'),
      ]);
      const [bd, wd] = await Promise.all([boardRes.json(), workersRes.json()]);
      setBoard(bd.board);
      setTasks(bd.tasks ?? []);
      setWorkers((wd.users ?? []).filter((u: IUser) => u.role === 'WORKER' && u.status === 'ACTIVE'));
      setLoading(false);
    }
    load();
  }, [id]);

  async function handleCreateTask(e: React.FormEvent) {
    e.preventDefault();
    if (!board) return;
    setSaving(true);
    try {
      const client = board.clientId as IClient;
      const checklistItems = taskForm.checklist ? taskForm.checklist.split('\n').filter(Boolean).map(t => ({ text: t.trim(), done: false })) : [];
      const body = {
        boardId: id,
        clientId: typeof client === 'string' ? client : client._id,
        title: taskForm.title,
        description: taskForm.description,
        taskType: taskForm.taskType,
        priority: taskForm.priority,
        assignedTo: taskForm.assignedTo || undefined,
        deadline: taskForm.deadline || undefined,
        platforms: selectedPlatforms,
        isOpenForClaim: taskForm.isOpenForClaim,
        checklist: checklistItems,
      };
      const res = await fetch('/api/tasks', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
      const data = await res.json();
      if (!res.ok) { toast.error(data.error); return; }
      setTasks(prev => [data.task, ...prev]);
      setShowTaskForm(false);
      setTaskForm(emptyTask);
      setSelectedPlatforms([]);
      toast.success('Task created');
    } finally { setSaving(false); }
  }

  async function updateTaskStatus(taskId: string, newStatus: TaskStatus) {
    setUpdatingTask(taskId);
    const res = await fetch(`/api/tasks/${taskId}`, {
      method: 'PUT', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ status: newStatus }),
    });
    const data = await res.json();
    if (res.ok) {
      setTasks(prev => prev.map(t => t._id === taskId ? data.task : t));
    }
    setUpdatingTask(null);
  }

  const tasksByStatus = STATUSES.reduce<Record<string, ITask[]>>((acc, s) => {
    acc[s.key] = tasks.filter(t => t.status === s.key);
    return acc;
  }, {});

  if (loading) return <div className="flex-1 flex items-center justify-center"><LoadingSpinner size={32} /></div>;
  if (!board) return <div className="p-6 text-red-400">Board not found.</div>;

  const client = board.clientId as IClient;
  const cp = board.contentPlan;
  const totalGenerated = board.autoGeneratedTasksCount ?? 0;
  const doneTasks = tasks.filter(t => t.status === 'DONE' || t.status === 'POSTED').length;
  const pendingTasks = tasks.length - doneTasks;

  return (
    <>
      <Topbar
        title={board.title}
        subtitle={client?.name}
        actions={
          <div className="flex items-center gap-2">
            <Button size="sm" onClick={() => setShowTaskForm(true)}><Plus size={13} />Add Task</Button>
            <Link href="/boards"><Button variant="secondary" size="sm"><ArrowLeft size={13} />Back</Button></Link>
          </div>
        }
      />
      {/* Content plan summary — only shown when a content plan exists */}
      {cp && (
        <div className="px-6 pt-4 pb-2 flex flex-wrap gap-3">
          {/* Monthly plan card */}
          <div className="rounded-xl border p-4 flex-1 min-w-[260px]" style={{ background: 'var(--bg-card)', borderColor: 'var(--border)' }}>
            <p className="text-xs font-semibold uppercase tracking-wider mb-3" style={{ color: 'var(--text-muted)' }}>Monthly Plan</p>
            <div className="grid grid-cols-3 gap-y-2 gap-x-4">
              {[
                { icon: <FileText size={12} />, label: 'Posts', value: cp.posts },
                { icon: <Video size={12} />, label: 'Reels', value: cp.reels },
                { icon: <Image size={12} />, label: 'Stories', value: cp.stories },
                { icon: <Camera size={12} />, label: 'Photoshoots', value: cp.photoshoots },
                { icon: <Video size={12} />, label: 'Video Shoots', value: cp.videoShoots },
                { icon: <Zap size={12} />, label: 'Drone Shoots', value: cp.droneShoots },
              ].filter(item => item.value > 0).map(item => (
                <div key={item.label} className="flex items-center gap-1.5">
                  <span style={{ color: 'var(--text-muted)' }}>{item.icon}</span>
                  <span className="text-xs" style={{ color: 'var(--text-secondary)' }}>
                    <span className="font-semibold" style={{ color: 'var(--text-primary)' }}>{item.value}</span> {item.label}
                  </span>
                </div>
              ))}
            </div>
          </div>
          {/* Generated tasks summary card */}
          {totalGenerated > 0 && (
            <div className="rounded-xl border p-4 min-w-[200px]" style={{ background: 'var(--bg-card)', borderColor: 'var(--border)' }}>
              <p className="text-xs font-semibold uppercase tracking-wider mb-3" style={{ color: 'var(--text-muted)' }}>Generated Tasks</p>
              <div className="space-y-1.5">
                <div className="flex items-center justify-between gap-4">
                  <span className="text-xs" style={{ color: 'var(--text-secondary)' }}>Total</span>
                  <span className="text-sm font-bold flex items-center gap-1" style={{ color: 'var(--text-primary)' }}>
                    <Zap size={12} className="text-amber-400" />{totalGenerated}
                  </span>
                </div>
                <div className="flex items-center justify-between gap-4">
                  <span className="text-xs" style={{ color: 'var(--text-secondary)' }}>Done</span>
                  <span className="text-sm font-semibold text-emerald-400">{doneTasks}</span>
                </div>
                <div className="flex items-center justify-between gap-4">
                  <span className="text-xs" style={{ color: 'var(--text-secondary)' }}>Pending</span>
                  <span className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>{pendingTasks}</span>
                </div>
                <div className="pt-1.5">
                  <div className="h-1.5 rounded-full overflow-hidden" style={{ background: 'var(--bg-elevated)' }}>
                    <div className="h-1.5 rounded-full bg-emerald-500 transition-all"
                      style={{ width: tasks.length > 0 ? `${(doneTasks / tasks.length) * 100}%` : '0%' }} />
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      )}

      <div className="flex-1 overflow-x-auto">
        <div className="flex gap-4 p-6 min-w-max">
          {STATUSES.map(col => (
            <div key={col.key} className="w-72 flex-shrink-0">
              <div className="flex items-center gap-2 mb-3 px-1">
                <div className="w-2 h-2 rounded-full" style={{ background: col.color }} />
                <span className="text-xs font-semibold uppercase tracking-wide" style={{ color: 'var(--text-secondary)' }}>{col.label}</span>
                <span className="ml-auto text-xs px-1.5 py-0.5 rounded-full" style={{ background: 'var(--bg-elevated)', color: 'var(--text-muted)' }}>{tasksByStatus[col.key]?.length ?? 0}</span>
              </div>

              <div className="space-y-2 min-h-[200px]">
                {(tasksByStatus[col.key] ?? []).length === 0 ? (
                  <div className="rounded-lg border border-dashed p-4 text-center" style={{ borderColor: 'var(--border)' }}>
                    <p className="text-xs" style={{ color: 'var(--text-muted)' }}>No tasks</p>
                  </div>
                ) : (
                  (tasksByStatus[col.key] ?? []).map(task => {
                    const worker = task.assignedTo as IUser | undefined;
                    const overdue = isOverdue(task.deadline) && !['DONE', 'POSTED', 'CANCELLED'].includes(task.status);
                    const checklist = task.checklist ?? [];
                    const done = checklist.filter(c => c.done).length;
                    return (
                      <div key={task._id} className="rounded-xl border p-3 hover:border-indigo-500/30 transition-all duration-150" style={{ background: 'var(--bg-card)', borderColor: 'var(--border)' }}>
                        <div className="flex items-start justify-between gap-2 mb-2">
                          <Link href={`/tasks/${task._id}`} className="text-xs font-medium leading-tight hover:text-indigo-300 transition-colors" style={{ color: 'var(--text-primary)' }}>
                            {task.title}
                          </Link>
                          <PriorityBadge priority={task.priority} />
                        </div>

                        <div className="flex flex-wrap gap-1 mb-2">
                          {task.platforms?.slice(0, 2).map(p => <PlatformBadge key={p} platform={p} />)}
                        </div>

                        {checklist.length > 0 && (
                          <div className="flex items-center gap-1.5 mb-2">
                            <CheckSquare size={11} style={{ color: 'var(--text-muted)' }} />
                            <div className="flex-1 h-1 rounded-full" style={{ background: 'var(--bg-elevated)' }}>
                              <div className="h-1 rounded-full bg-emerald-500" style={{ width: `${(done / checklist.length) * 100}%` }} />
                            </div>
                            <span className="text-xs" style={{ color: 'var(--text-muted)' }}>{done}/{checklist.length}</span>
                          </div>
                        )}

                        <div className="flex items-center justify-between mt-2">
                          <div className="flex items-center gap-1.5">
                            {worker && (
                              <div className="w-5 h-5 rounded-full flex items-center justify-center text-xs font-bold" style={{ background: 'linear-gradient(135deg, #6366f1, #8b5cf6)', color: 'white' }}>
                                {(worker as IUser).name?.charAt(0)}
                              </div>
                            )}
                            {!worker && task.isOpenForClaim && <span className="text-xs text-yellow-400">Open</span>}
                          </div>
                          <div className="flex items-center gap-1">
                            {overdue && <AlertCircle size={11} className="text-red-400" />}
                            {task.deadline && <span className={`text-xs ${overdue ? 'text-red-400' : ''}`} style={!overdue ? { color: 'var(--text-muted)' } : undefined}>{formatDate(task.deadline)}</span>}
                          </div>
                        </div>

                        <div className="mt-2 pt-2 border-t" style={{ borderColor: 'var(--border-subtle)' }}>
                          <select
                            value={task.status}
                            disabled={updatingTask === task._id}
                            onChange={e => updateTaskStatus(task._id, e.target.value as TaskStatus)}
                            className="w-full text-xs px-2 py-1 rounded cursor-pointer"
                            style={{ background: 'var(--bg-elevated)', borderColor: 'transparent', color: 'var(--text-secondary)' }}
                          >
                            {STATUSES.map(s => <option key={s.key} value={s.key} style={{ background: 'var(--bg-elevated)' }}>{s.label}</option>)}
                          </select>
                        </div>
                      </div>
                    );
                  })
                )}
              </div>
            </div>
          ))}
        </div>
      </div>

      <Modal open={showTaskForm} onClose={() => setShowTaskForm(false)} title="Create Task" size="lg"
        footer={<><Button variant="secondary" onClick={() => setShowTaskForm(false)}>Cancel</Button><Button onClick={handleCreateTask} loading={saving}>Create Task</Button></>}>
        <form onSubmit={handleCreateTask} className="space-y-4">
          <Input label="Task Title *" value={taskForm.title} onChange={e => setTaskForm(p => ({ ...p, title: e.target.value }))} required placeholder="e.g. Monthly Photoshoot" />
          <Textarea label="Description" value={taskForm.description} onChange={e => setTaskForm(p => ({ ...p, description: e.target.value }))} rows={2} />
          <div className="grid grid-cols-2 gap-3">
            <Select label="Task Type" value={taskForm.taskType} onChange={e => setTaskForm(p => ({ ...p, taskType: e.target.value as TaskType }))} options={TASK_TYPES} />
            <Select label="Priority" value={taskForm.priority} onChange={e => setTaskForm(p => ({ ...p, priority: e.target.value as TaskPriority }))}
              options={[{ value: 'LOW', label: 'Low' }, { value: 'MEDIUM', label: 'Medium' }, { value: 'HIGH', label: 'High' }, { value: 'URGENT', label: 'Urgent' }]} />
          </div>
          <div className="grid grid-cols-2 gap-3">
            <Select label="Assign to Worker" value={taskForm.assignedTo} onChange={e => setTaskForm(p => ({ ...p, assignedTo: e.target.value }))}
              options={[{ value: '', label: '— Open for Claim —' }, ...workers.map(w => ({ value: w._id, label: w.name }))]} />
            <Input label="Deadline" type="date" value={taskForm.deadline} onChange={e => setTaskForm(p => ({ ...p, deadline: e.target.value }))} />
          </div>
          <div>
            <label className="text-xs font-medium block mb-2" style={{ color: 'var(--text-secondary)' }}>Platforms</label>
            <div className="flex flex-wrap gap-2">
              {PLATFORMS.map(p => (
                <button key={p} type="button"
                  onClick={() => setSelectedPlatforms(prev => prev.includes(p) ? prev.filter(x => x !== p) : [...prev, p])}
                  className="px-3 py-1 rounded-full text-xs font-medium transition-all border"
                  style={{ background: selectedPlatforms.includes(p) ? 'rgba(99,102,241,0.2)' : 'var(--bg-elevated)', borderColor: selectedPlatforms.includes(p) ? '#6366f1' : 'var(--border)', color: selectedPlatforms.includes(p) ? '#a5b4fc' : 'var(--text-secondary)' }}>
                  {p}
                </button>
              ))}
            </div>
          </div>
          <div className="flex items-center gap-2">
            <input type="checkbox" id="openForClaim" checked={taskForm.isOpenForClaim} onChange={e => setTaskForm(p => ({ ...p, isOpenForClaim: e.target.checked }))} className="rounded" />
            <label htmlFor="openForClaim" className="text-sm" style={{ color: 'var(--text-secondary)' }}>Open for workers to claim</label>
          </div>
          <Textarea label="Checklist (one item per line)" value={taskForm.checklist} onChange={e => setTaskForm(p => ({ ...p, checklist: e.target.value }))} rows={3} placeholder="Set up equipment&#10;Shoot food photos&#10;Transfer files" />
        </form>
      </Modal>
    </>
  );
}
