export type UserRole = 'CEO' | 'WORKER';
export type UserStatus = 'ACTIVE' | 'INACTIVE';

export type ClientStatus =
  | 'LEAD'
  | 'OFFER_SENT'
  | 'WAITING_RESPONSE'
  | 'ACCEPTED'
  | 'ACTIVE'
  | 'INACTIVE'
  | 'REJECTED'
  | 'PAUSED'
  | 'CLOSED';

export type DocLang = 'en' | 'sq' | 'mk';

export type AgreementType = 'OFFER' | 'CONTRACT' | 'INVOICE' | 'OTHER';

export type BoardStatus = 'DRAFT' | 'ACTIVE' | 'COMPLETED' | 'ARCHIVED';

export type TaskStatus =
  | 'CONTENT_PREPARATION'
  | 'QUALITY_ASSURANCE'
  | 'POST_VERIFIED'
  | 'READY_TO_POST'
  | 'POSTED'
  | 'NEEDS_FIX';

export type TaskPriority = 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';

export type Platform = 'Instagram' | 'Facebook' | 'TikTok' | 'YouTube' | 'Website';

export type ContentType = 'POST' | 'REEL' | 'STORY' | 'CAROUSEL' | 'VIDEO' | 'PHOTO' | 'OTHER';

export type ContentStatus =
  | 'IDEA'
  | 'IN_PRODUCTION'
  | 'EDITING'
  | 'WAITING_APPROVAL'
  | 'APPROVED'
  | 'SCHEDULED'
  | 'POSTED'
  | 'REPORTED';

export type PaymentStatus = 'PAID' | 'UNPAID' | 'PARTIAL' | 'LATE';
export type PaymentMethod = 'CASH' | 'BANK' | 'CARD' | 'OTHER';

export interface IUser {
  _id: string;
  name: string;
  email: string;
  role: UserRole;
  avatarUrl?: string;
  phone?: string;
  status: UserStatus;
  createdAt: string;
  updatedAt: string;
}

export interface IClient {
  _id: string;
  name: string;
  businessType?: string;
  contactPerson?: string;
  phone?: string;
  email?: string;
  instagramUrl?: string;
  facebookUrl?: string;
  tiktokUrl?: string;
  websiteUrl?: string;
  address?: string;
  packageName?: string;
  monthlyPrice?: number;
  currency?: string;
  status: ClientStatus;
  startDate?: string;
  notes?: string;
  brandColors?: string[];
  logoUrl?: string;
  driveFolderUrl?: string;
  isDemo?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface IGeneratedDocument {
  _id: string;
  clientId: string;
  documentType: 'offer' | 'agreement';
  language: DocLang;
  title: string;
  generatedBy: string | IUser;
  documentData: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
}

export interface IAgreement {
  _id: string;
  clientId: string;
  title: string;
  fileUrl?: string;
  fileName?: string;
  agreementType: AgreementType;
  startDate?: string;
  endDate?: string;
  notes?: string;
  uploadedBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface IContentPlan {
  posts: number;
  reels: number;
  stories: number;
  photoshoots: number;
  videoShoots: number;
  droneShoots: number;
  reports: number;
}

export type DeadlinePattern = 'NONE' | 'SPREAD' | 'SAME';

export interface IBoard {
  _id: string;
  clientId: string | IClient;
  title: string;
  month: number;
  year: number;
  description?: string;
  status: BoardStatus;
  createdBy: string;
  contentPlan?: IContentPlan;
  autoGeneratedTasksCount?: number;
  generatedAt?: string;
  isDemo?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface IChecklist {
  _id?: string;
  text: string;
  done: boolean;
}

export interface ILink {
  _id?: string;
  label: string;
  url: string;
  type?: string;
}

export interface IComment {
  _id?: string;
  userId: string | IUser;
  text: string;
  createdAt: string;
}

export type ReportStatus = 'NOT_POSTED' | 'WAITING_FOR_REPORT_TIME' | 'NEEDS_REPORT_DATA' | 'COMPLETED';

export interface IMetrics {
  views?: number;
  reach?: number;
  likes?: number;
  comments?: number;
  shares?: number;
  saves?: number;
  profileVisits?: number;
  linkClicks?: number;
  storyReplies?: number;
  storyTapsForward?: number;
  storyTapsBack?: number;
  storyExits?: number;
  engagementRate?: number;
  notes?: string;
  screenshotUrl?: string;
}

export interface IReporting {
  reportDueAt?: string;
  reportStatus: ReportStatus;
  reportCompletedAt?: string;
  metrics?: IMetrics;
}

export type PostedLinkPlatform = 'Instagram' | 'Facebook' | 'TikTok' | 'YouTube' | 'Website' | 'Other';

export interface IPostedLink {
  _id: string;
  platform: PostedLinkPlatform;
  url: string;
  addedBy: string | IUser;
  addedAt: string;
}

export interface ITask {
  _id: string;
  boardId: string | IBoard;
  clientId: string | IClient;
  title: string;
  description?: string;
  contentType: ContentType;
  status: TaskStatus;
  priority: TaskPriority;
  platforms?: Platform[];
  assignedTo?: string | IUser;
  claimedBy?: string | IUser;
  createdBy: string | IUser;
  deadline?: string;
  scheduledDate?: string;
  postedDate?: string;
  checklist?: IChecklist[];
  links?: ILink[];
  comments?: IComment[];
  reporting?: IReporting;
  postedLinks?: IPostedLink[];
  primaryPostUrl?: string;
  isOpenForClaim: boolean;
  autoGenerated?: boolean;
  isDemo?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface IContentItem {
  _id: string;
  clientId: string | IClient;
  boardId?: string | IBoard;
  taskId?: string | ITask;
  title: string;
  contentType: ContentType;
  caption?: string;
  platforms?: Platform[];
  scheduledDate?: string;
  postedDate?: string;
  status: ContentStatus;
  mediaUrl?: string;
  designUrl?: string;
  notes?: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface IPayment {
  _id: string;
  clientId: string | IClient;
  month: number;
  year: number;
  amount: number;
  currency: string;
  status: PaymentStatus;
  dueDate?: string;
  paidDate?: string;
  paymentMethod?: PaymentMethod;
  invoiceUrl?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface IReport {
  _id: string;
  clientId: string | IClient;
  contentItemId?: string | IContentItem;
  taskId?: string | ITask;
  reportDate: string;
  daysAfterPosting?: number;
  views?: number;
  reach?: number;
  likes?: number;
  comments?: number;
  shares?: number;
  saves?: number;
  clicks?: number;
  engagementRate?: number;
  notes?: string;
  screenshotUrl?: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface IActivityLog {
  _id: string;
  userId: string | IUser;
  action: string;
  entityType: string;
  entityId?: string;
  message: string;
  createdAt: string;
}

export interface JWTPayload {
  userId: string;
  email: string;
  role: UserRole;
  name: string;
}

// ─── Photoshoot Day Flow ───────────────────────────────────────────────────────

export type PhotoshootStatus = 'PLANNED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';

export type ShotCategory =
  | 'Food' | 'Product' | 'Interior' | 'Exterior' | 'Staff'
  | 'Behind the Scenes' | 'Detail Shot' | 'Lifestyle'
  | 'Video' | 'Reel' | 'Story' | 'Drone' | 'Other';

export interface IShotItem {
  _id: string;
  title: string;
  description?: string;
  category: ShotCategory;
  required: boolean;
  completed: boolean;
  completedBy?: string | IUser;
  completedAt?: string;
  notes?: string;
  sampleImageUrl?: string;
  priority: 'LOW' | 'MEDIUM' | 'HIGH';
  order: number;
}

export interface IPhotoshootSession {
  _id: string;
  clientId: string | IClient;
  title: string;
  description?: string;
  shootDate: string;
  startTime: string;
  endTime?: string;
  location: string;
  address?: string;
  assignedWorkers: (string | IUser)[];
  status: PhotoshootStatus;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
  notes?: string;
  equipmentNeeded: string[];
  clientContactName?: string;
  clientContactPhone?: string;
  shotList: IShotItem[];
  createdBy: string | IUser;
  isDemo?: boolean;
  createdAt: string;
  updatedAt: string;
}
