export type UserRole = 'CEO' | 'WORKER' | 'CLIENT';
export type UserStatus = 'ACTIVE' | 'INACTIVE';

export type ClientStatus =
  | 'LEAD'
  | 'OFFER_SENT'
  | 'WAITING_RESPONSE'
  | 'ACCEPTED'
  | 'ACTIVE'
  | 'INACTIVE'
  | 'REJECTED'
  | 'PAUSED'
  | 'CLOSED';

export type DocLang = 'en' | 'sq' | 'mk';

export type AgreementType = 'OFFER' | 'CONTRACT' | 'INVOICE' | 'OTHER';

export type BoardStatus = 'DRAFT' | 'ACTIVE' | 'COMPLETED' | 'ARCHIVED';

export type TaskStatus =
  | 'CONTENT_PREPARATION'
  | 'QUALITY_ASSURANCE'
  | 'POST_VERIFIED'
  | 'READY_TO_POST'
  | 'POSTED'
  | 'NEEDS_FIX';

export type TaskPriority = 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';

export type Platform = 'Instagram' | 'Facebook' | 'TikTok' | 'YouTube' | 'Website';

export type ContentType = 'POST' | 'REEL' | 'STORY' | 'CAROUSEL' | 'VIDEO' | 'PHOTO' | 'OTHER';

export type ContentStatus =
  | 'IDEA'
  | 'IN_PRODUCTION'
  | 'EDITING'
  | 'WAITING_APPROVAL'
  | 'APPROVED'
  | 'SCHEDULED'
  | 'POSTED'
  | 'REPORTED';

export type PaymentMethod = 'CASH' | 'BANK' | 'CARD' | 'OTHER';

export interface IUser {
  _id: string;
  name: string;
  email: string;
  role: UserRole;
  clientId?: string | IClient;
  avatarUrl?: string;
  phone?: string;
  status: UserStatus;
  createdAt: string;
  updatedAt: string;
}

export interface IClient {
  _id: string;
  name: string;
  businessType?: string;
  contactPerson?: string;
  phone?: string;
  email?: string;
  instagramUrl?: string;
  facebookUrl?: string;
  tiktokUrl?: string;
  websiteUrl?: string;
  address?: string;
  packageName?: string;
  monthlyPrice?: number;
  currency?: string;
  status: ClientStatus;
  startDate?: string;
  notes?: string;
  brandColors?: string[];
  logoUrl?: string;
  driveFolderUrl?: string;
  isDemo?: boolean;
  billing?: IClientBilling;
  createdAt: string;
  updatedAt: string;
}

export interface IGeneratedDocument {
  _id: string;
  clientId: string;
  documentType: 'offer' | 'agreement';
  language: DocLang;
  title: string;
  generatedBy: string | IUser;
  documentData: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
}

export interface IAgreement {
  _id: string;
  clientId: string;
  title: string;
  fileUrl?: string;
  fileName?: string;
  agreementType: AgreementType;
  startDate?: string;
  endDate?: string;
  notes?: string;
  uploadedBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface IContentPlan {
  posts: number;
  reels: number;
  stories: number;
  photoshoots: number;
  videoShoots: number;
  droneShoots: number;
  reports: number;
}

export type DeadlinePattern = 'NONE' | 'SPREAD' | 'SAME';

export interface IBoard {
  _id: string;
  clientId: string | IClient;
  title: string;
  month: number;
  year: number;
  description?: string;
  status: BoardStatus;
  createdBy: string;
  contentPlan?: IContentPlan;
  autoGeneratedTasksCount?: number;
  generatedAt?: string;
  isDemo?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface IChecklist {
  _id?: string;
  text: string;
  done: boolean;
}

export interface ILink {
  _id?: string;
  label: string;
  url: string;
  type?: string;
}

export interface IComment {
  _id?: string;
  userId: string | IUser;
  text: string;
  createdAt: string;
}

export type ReportStatus = 'NOT_POSTED' | 'WAITING_FOR_REPORT_TIME' | 'NEEDS_REPORT_DATA' | 'COMPLETED';

export interface IMetrics {
  views?: number;
  reach?: number;
  likes?: number;
  comments?: number;
  shares?: number;
  saves?: number;
  profileVisits?: number;
  linkClicks?: number;
  storyReplies?: number;
  storyTapsForward?: number;
  storyTapsBack?: number;
  storyExits?: number;
  engagementRate?: number;
  notes?: string;
  screenshotUrl?: string;
}

export interface IReporting {
  reportDueAt?: string;
  reportStatus: ReportStatus;
  reportCompletedAt?: string;
  metrics?: IMetrics;
}

export type PostedLinkPlatform = 'Instagram' | 'Facebook' | 'TikTok' | 'YouTube' | 'Website' | 'Other';

export interface IPostedLink {
  _id: string;
  platform: PostedLinkPlatform;
  url: string;
  addedBy: string | IUser;
  addedAt: string;
}

export interface ITask {
  _id: string;
  boardId: string | IBoard;
  clientId: string | IClient;
  title: string;
  description?: string;
  contentType: ContentType;
  status: TaskStatus;
  priority: TaskPriority;
  platforms?: Platform[];
  assignedTo?: string | IUser;
  claimedBy?: string | IUser;
  createdBy: string | IUser;
  deadline?: string;
  scheduledDate?: string;
  postedDate?: string;
  checklist?: IChecklist[];
  links?: ILink[];
  comments?: IComment[];
  reporting?: IReporting;
  postedLinks?: IPostedLink[];
  primaryPostUrl?: string;
  isOpenForClaim: boolean;
  autoGenerated?: boolean;
  isDemo?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface IContentItem {
  _id: string;
  clientId: string | IClient;
  boardId?: string | IBoard;
  taskId?: string | ITask;
  title: string;
  contentType: ContentType;
  caption?: string;
  platforms?: Platform[];
  scheduledDate?: string;
  postedDate?: string;
  status: ContentStatus;
  mediaUrl?: string;
  designUrl?: string;
  notes?: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export type MonthlyReportStatus = 'DRAFT' | 'FINALIZED';

export interface IMonthlyReportStats {
  boardTitles: string[];
  totalPlanned: number;
  totalPosted: number;
  totalNotCompleted: number;
  byType: Record<string, number>;
  completedShoots: number;
  postedLinks: { taskId: string; title: string; contentType: string; url: string }[];
}

export interface IMonthlyReportMetrics {
  followersStart?: number;
  followersEnd?: number;
  totalReach?: number;
  totalViews?: number;
  profileVisits?: number;
  engagementRatePct?: number;
  facebookReach?: number;
  tiktokViews?: number;
}

export interface IMonthlyReport {
  _id: string;
  clientId: string | IClient;
  month: number;
  year: number;
  status: MonthlyReportStatus;
  language: 'en' | 'sq';
  stats: IMonthlyReportStats;
  metrics: IMonthlyReportMetrics;
  summary?: string;
  highlights?: string;
  bestPerformingContent?: string;
  observations?: string;
  recommendations?: string;
  nextMonthPlan?: string;
  createdBy: string | IUser;
  finalizedAt?: string;
  finalizedBy?: string | IUser;
  createdAt: string;
  updatedAt: string;
}

export interface IActivityLog {
  _id: string;
  userId: string | IUser;
  action: string;
  entityType: string;
  entityId?: string;
  message: string;
  createdAt: string;
}

export interface JWTPayload {
  userId: string;
  email: string;
  role: UserRole;
  name: string;
  clientId?: string;
}


// ─── Billing & Client Portal ───────────────────────────────────────────────────

/**
 * All monetary amounts in the billing module are stored in minor units
 * (e.g. cents for EUR/USD) to avoid floating-point rounding errors.
 * Use toMinorUnits()/fromMinorUnits()/formatMoney() from '@/lib/billing'.
 */
export interface IClientBilling {
  monthlyFeeMinor: number;
  currency: string;
  billingStartDate?: string;
  billingDay: number;
  paymentTerms?: string;
  billingEnabled: boolean;
  notes?: string;
}

export type BillingPeriodStatus = 'UNPAID' | 'PARTIALLY_PAID' | 'PAID' | 'OVERPAID';

export interface IBillingPeriod {
  _id: string;
  clientId: string | IClient;
  year: number;
  month: number;
  expectedAmountMinor: number;
  currency: string;
  verifiedPaidAmountMinor: number;
  status: BillingPeriodStatus;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export type PaymentVerificationStatus = 'PENDING_CONFIRMATION' | 'VERIFIED' | 'DISPUTED' | 'CANCELLED';

export type DisputeReason = 'WRONG_AMOUNT' | 'WRONG_DATE' | 'NOT_MADE' | 'DUPLICATE' | 'OTHER';

export interface IPaymentAllocation {
  billingPeriodId: string | IBillingPeriod;
  amountMinor: number;
}

export interface IPaymentEditHistoryEntry {
  editedAt: string;
  editedBy: string | IUser;
  changes: Record<string, { from: unknown; to: unknown }>;
}

export interface IPaymentDisputeResolution {
  resolvedAt: string;
  resolvedBy: string | IUser;
  action: 'EDITED' | 'CANCELLED' | 'RESENT' | 'DISMISSED';
  note?: string;
}

export interface IClientPayment {
  _id: string;
  clientId: string | IClient;
  amountMinor: number;
  currency: string;
  paymentDate: string;
  paymentMethod: PaymentMethod;
  reference?: string;
  notes?: string;
  allocations: IPaymentAllocation[];
  creditAmountMinor: number;
  verificationStatus: PaymentVerificationStatus;
  destinationWalletId?: string | IWallet;
  linkedFinanceTransactionId?: string;
  createdBy: string | IUser;
  verifiedAt?: string;
  verifiedBy?: string | IUser;
  disputedAt?: string;
  disputeReason?: DisputeReason;
  disputeMessage?: string;
  disputedBy?: string | IUser;
  disputeResolution?: IPaymentDisputeResolution;
  cancelledAt?: string;
  cancelledBy?: string | IUser;
  editHistory?: IPaymentEditHistoryEntry[];
  createdAt: string;
  updatedAt: string;
}

// ─── Company Finance ────────────────────────────────────────────────────────

export type WalletType = 'PERSONAL' | 'COMPANY' | 'SAVINGS';

export interface IWallet {
  _id: string;
  name: string;
  type: WalletType;
  ownerUserId?: string | IUser;
  isActive: boolean;
  order: number;
  balanceMinor: number;
  createdAt: string;
  updatedAt: string;
}

export type FinanceTransactionType = 'INCOME' | 'EXPENSE' | 'TRANSFER';
export type FinanceTransactionStatus = 'ACTIVE' | 'VOIDED';

export interface IFinanceEditHistoryEntry {
  editedAt: string;
  editedBy: string | IUser;
  changes: Record<string, { from: unknown; to: unknown }>;
}

export interface IFinanceTransaction {
  _id: string;
  type: FinanceTransactionType;
  status: FinanceTransactionStatus;
  category?: string;
  description?: string;
  clientId?: string | IClient;
  reference?: string;
  notes?: string;
  originalAmountMinor: number;
  originalCurrency: string;
  exchangeRate: number;
  baseAmountMinor: number;
  walletId?: string | IWallet;
  fromWalletId?: string | IWallet;
  toWalletId?: string | IWallet;
  transactionDate: string;
  createdBy: string | IUser;
  sourcePaymentId?: string;
  voidedAt?: string;
  voidedBy?: string | IUser;
  voidReason?: string;
  editHistory?: IFinanceEditHistoryEntry[];
  createdAt: string;
  updatedAt: string;
}

// ─── Bookings / Availability ────────────────────────────────────────────────

export type ShootType = 'PHOTO_SHOOT' | 'VIDEO_SHOOT' | 'PHOTO_VIDEO' | 'CONTENT_SESSION' | 'OTHER';
export type BookingStatus = 'PENDING' | 'SUGGESTED' | 'APPROVED' | 'REJECTED' | 'CANCELLED';

export interface IBooking {
  _id: string;
  clientId: string | IClient;
  date: string;
  startTime: string;
  endTime: string;
  shootType: ShootType;
  notes?: string;
  status: BookingStatus;
  requestedBy: string | IUser;
  reviewedBy?: string | IUser;
  reviewedAt?: string;
  rejectionReason?: string;
  suggestedDate?: string;
  suggestedStartTime?: string;
  suggestedEndTime?: string;
  createdAt: string;
  updatedAt: string;
}

/** A calendar entry as returned by /api/bookings/availability — full detail for CEO/own bookings, masked for other clients. */
export interface IAvailabilityEntry {
  _id?: string;
  clientId?: string;
  clientName?: string;
  date: string;
  startTime: string;
  endTime: string;
  shootType?: ShootType;
  notes?: string;
  status: BookingStatus | 'BUSY';
}
