export type UserRole = 'CEO' | 'WORKER';
export type UserStatus = 'ACTIVE' | 'INACTIVE';

export type ClientStatus = 'ACTIVE' | 'PAUSED' | 'CLOSED';

export type AgreementType = 'OFFER' | 'CONTRACT' | 'INVOICE' | 'OTHER';

export type BoardStatus = 'ACTIVE' | 'ARCHIVED';

export type TaskType =
  | 'PHOTOSHOOT'
  | 'VIDEO_SHOOT'
  | 'DRONE'
  | 'EDITING'
  | 'REEL'
  | 'STORY'
  | 'POST_DESIGN'
  | 'COPYWRITING'
  | 'CLIENT_APPROVAL'
  | 'POSTING'
  | 'REPORTING'
  | 'PAYMENT'
  | 'MEETING'
  | 'OTHER';

export type TaskStatus =
  | 'TO_DO'
  | 'IN_PROGRESS'
  | 'WAITING_APPROVAL'
  | 'APPROVED'
  | 'SCHEDULED'
  | 'POSTED'
  | 'DONE'
  | 'CANCELLED';

export type TaskPriority = 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';

export type Platform = 'Instagram' | 'Facebook' | 'TikTok' | 'YouTube' | 'Website';

export type ContentType = 'POST' | 'REEL' | 'STORY' | 'CAROUSEL' | 'VIDEO' | 'PHOTO' | 'AD';

export type ContentStatus =
  | 'IDEA'
  | 'IN_PRODUCTION'
  | 'EDITING'
  | 'WAITING_APPROVAL'
  | 'APPROVED'
  | 'SCHEDULED'
  | 'POSTED'
  | 'REPORTED';

export type PaymentStatus = 'PAID' | 'UNPAID' | 'PARTIAL' | 'LATE';
export type PaymentMethod = 'CASH' | 'BANK' | 'CARD' | 'OTHER';

export interface IUser {
  _id: string;
  name: string;
  email: string;
  role: UserRole;
  avatarUrl?: string;
  phone?: string;
  status: UserStatus;
  createdAt: string;
  updatedAt: string;
}

export interface IClient {
  _id: string;
  name: string;
  businessType?: string;
  contactPerson?: string;
  phone?: string;
  email?: string;
  instagramUrl?: string;
  facebookUrl?: string;
  tiktokUrl?: string;
  websiteUrl?: string;
  address?: string;
  packageName?: string;
  monthlyPrice?: number;
  currency?: string;
  status: ClientStatus;
  startDate?: string;
  notes?: string;
  brandColors?: string[];
  logoUrl?: string;
  driveFolderUrl?: string;
  createdAt: string;
  updatedAt: string;
}

export interface IAgreement {
  _id: string;
  clientId: string;
  title: string;
  fileUrl?: string;
  fileName?: string;
  agreementType: AgreementType;
  startDate?: string;
  endDate?: string;
  notes?: string;
  uploadedBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface IContentPlan {
  posts: number;
  reels: number;
  stories: number;
  photoshoots: number;
  videoShoots: number;
  droneShoots: number;
  reports: number;
}

export type DeadlinePattern = 'NONE' | 'SPREAD' | 'SAME';

export interface IBoard {
  _id: string;
  clientId: string | IClient;
  title: string;
  month: number;
  year: number;
  description?: string;
  status: BoardStatus;
  createdBy: string;
  contentPlan?: IContentPlan;
  autoGeneratedTasksCount?: number;
  generatedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface IChecklist {
  _id?: string;
  text: string;
  done: boolean;
}

export interface IAttachment {
  _id?: string;
  name: string;
  url: string;
  type?: string;
}

export interface IComment {
  _id?: string;
  userId: string | IUser;
  text: string;
  createdAt: string;
}

export interface ITask {
  _id: string;
  boardId: string | IBoard;
  clientId: string | IClient;
  title: string;
  description?: string;
  taskType: TaskType;
  status: TaskStatus;
  priority: TaskPriority;
  assignedTo?: string | IUser;
  claimedBy?: string | IUser;
  createdBy: string | IUser;
  deadline?: string;
  startDate?: string;
  completedAt?: string;
  platforms?: Platform[];
  checklist?: IChecklist[];
  attachments?: IAttachment[];
  comments?: IComment[];
  isOpenForClaim: boolean;
  contentItemId?: string;
  autoGenerated?: boolean;
  generationGroup?: string;
  createdAt: string;
  updatedAt: string;
}

export interface IContentItem {
  _id: string;
  clientId: string | IClient;
  boardId?: string | IBoard;
  taskId?: string | ITask;
  title: string;
  contentType: ContentType;
  caption?: string;
  platforms?: Platform[];
  scheduledDate?: string;
  postedDate?: string;
  status: ContentStatus;
  mediaUrl?: string;
  designUrl?: string;
  notes?: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface IPayment {
  _id: string;
  clientId: string | IClient;
  month: number;
  year: number;
  amount: number;
  currency: string;
  status: PaymentStatus;
  dueDate?: string;
  paidDate?: string;
  paymentMethod?: PaymentMethod;
  invoiceUrl?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface IReport {
  _id: string;
  clientId: string | IClient;
  contentItemId?: string | IContentItem;
  taskId?: string | ITask;
  reportDate: string;
  daysAfterPosting?: number;
  views?: number;
  reach?: number;
  likes?: number;
  comments?: number;
  shares?: number;
  saves?: number;
  clicks?: number;
  engagementRate?: number;
  notes?: string;
  screenshotUrl?: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface IActivityLog {
  _id: string;
  userId: string | IUser;
  action: string;
  entityType: string;
  entityId?: string;
  message: string;
  createdAt: string;
}

export interface JWTPayload {
  userId: string;
  email: string;
  role: UserRole;
  name: string;
}
