import { NextRequest, NextResponse } from 'next/server';
import { connectDB } from '@/lib/mongodb';
import { getSession } from '@/lib/auth';
import Board from '@/models/Board';
import ActivityLog from '@/models/ActivityLog';
import { generateMonthlyBoardTasks } from '@/lib/generateMonthlyBoardTasks';

export async function GET(request: NextRequest) {
  const session = await getSession();
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  await connectDB();
  const { searchParams } = request.nextUrl;
  const clientId = searchParams.get('clientId');
  const status = searchParams.get('status');

  const query: Record<string, unknown> = {};
  if (clientId) query.clientId = clientId;
  if (status) query.status = status;

  const boards = await Board.find(query)
    .populate('clientId', 'name status')
    .sort({ year: -1, month: -1 });

  return NextResponse.json({ boards });
}

export async function POST(request: NextRequest) {
  const session = await getSession();
  if (!session || session.role !== 'CEO') return NextResponse.json({ error: 'Forbidden' }, { status: 403 });

  await connectDB();
  const body = await request.json();

  const {
    clientId, title, month, year, description,
    contentPlan,
    defaultAssignedWorker,
    isOpenForClaim = false,
    deadlinePattern = 'NONE',
    sameDeadline,
    platforms = [],
    confirmDuplicate = false,
  } = body;

  if (!clientId || !title || !month || !year) {
    return NextResponse.json({ error: 'clientId, title, month, year are required' }, { status: 400 });
  }

  // Duplicate check
  const existing = await Board.findOne({ clientId, month: Number(month), year: Number(year) });
  if (existing && !confirmDuplicate) {
    return NextResponse.json(
      { error: 'DUPLICATE_BOARD', message: `A board for this client already exists for ${new Date(year, month - 1).toLocaleString('en-US', { month: 'long' })} ${year}.` },
      { status: 409 }
    );
  }

  const hasContentPlan = contentPlan && (
    (contentPlan.posts ?? 0) > 0 ||
    (contentPlan.reels ?? 0) > 0 ||
    (contentPlan.stories ?? 0) > 0 ||
    (contentPlan.photoshoots ?? 0) > 0 ||
    (contentPlan.videoShoots ?? 0) > 0 ||
    (contentPlan.droneShoots ?? 0) > 0
  );

  const board = await Board.create({
    clientId,
    title,
    month: Number(month),
    year: Number(year),
    description,
    createdBy: session.userId,
    ...(hasContentPlan ? { contentPlan } : {}),
  });

  let generatedTaskCount = 0;

  if (hasContentPlan) {
    const result = await generateMonthlyBoardTasks({
      boardId: String(board._id),
      clientId,
      month: Number(month),
      year: Number(year),
      numberOfPosts: contentPlan.posts ?? 0,
      numberOfReels: contentPlan.reels ?? 0,
      numberOfStories: contentPlan.stories ?? 0,
      numberOfPhotoshoots: contentPlan.photoshoots ?? 0,
      numberOfVideoShoots: contentPlan.videoShoots ?? 0,
      numberOfDroneShoots: contentPlan.droneShoots ?? 0,
      platforms,
      defaultAssignedWorker: defaultAssignedWorker || undefined,
      isOpenForClaim,
      deadlinePattern,
      sameDeadline,
      createdBy: session.userId,
    });

    generatedTaskCount = result.taskCount;

    await Board.findByIdAndUpdate(board._id, {
      autoGeneratedTasksCount: generatedTaskCount,
      generatedAt: new Date(),
    });
  }

  await ActivityLog.create({
    userId: session.userId,
    action: 'CREATE',
    entityType: 'Board',
    entityId: board._id,
    message: `Created board "${board.title}"${generatedTaskCount > 0 ? ` with ${generatedTaskCount} auto-generated tasks` : ''}`,
  });

  const populated = await Board.findById(board._id).populate('clientId', 'name status');
  return NextResponse.json({ board: populated }, { status: 201 });
}
