import mongoose, { Schema, Document, Model } from 'mongoose';

export interface IContentPlan {
  posts: number;
  reels: number;
  stories: number;
  photoshoots: number;
  videoShoots: number;
  droneShoots: number;
  reports: number;
}

export interface IBoardDoc extends Document {
  clientId: mongoose.Types.ObjectId;
  title: string;
  month: number;
  year: number;
  description?: string;
  status: 'ACTIVE' | 'ARCHIVED';
  createdBy: mongoose.Types.ObjectId;
  contentPlan?: IContentPlan;
  autoGeneratedTasksCount: number;
  generatedAt?: Date;
  isDemo: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const ContentPlanSchema = new Schema<IContentPlan>(
  {
    posts: { type: Number, default: 0 },
    reels: { type: Number, default: 0 },
    stories: { type: Number, default: 0 },
    photoshoots: { type: Number, default: 0 },
    videoShoots: { type: Number, default: 0 },
    droneShoots: { type: Number, default: 0 },
    reports: { type: Number, default: 0 },
  },
  { _id: false }
);

const BoardSchema = new Schema<IBoardDoc>(
  {
    clientId: { type: Schema.Types.ObjectId, ref: 'Client', required: true },
    title: { type: String, required: true },
    month: { type: Number, required: true, min: 1, max: 12 },
    year: { type: Number, required: true },
    description: { type: String },
    status: { type: String, enum: ['ACTIVE', 'ARCHIVED'], default: 'ACTIVE' },
    createdBy: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    contentPlan: { type: ContentPlanSchema },
    autoGeneratedTasksCount: { type: Number, default: 0 },
    generatedAt: { type: Date },
    isDemo: { type: Boolean, default: false },
  },
  { timestamps: true }
);

const Board: Model<IBoardDoc> = mongoose.models.Board ?? mongoose.model<IBoardDoc>('Board', BoardSchema);
export default Board;
