import mongoose, { Schema, Document, Model } from 'mongoose';

export interface ITaskDoc extends Document {
  boardId: mongoose.Types.ObjectId;
  clientId: mongoose.Types.ObjectId;
  title: string;
  description?: string;
  taskType: string;
  status: string;
  priority: string;
  assignedTo?: mongoose.Types.ObjectId;
  claimedBy?: mongoose.Types.ObjectId;
  createdBy: mongoose.Types.ObjectId;
  deadline?: Date;
  startDate?: Date;
  completedAt?: Date;
  platforms?: string[];
  checklist?: { text: string; done: boolean }[];
  attachments?: { name: string; url: string; type?: string }[];
  comments?: { userId: mongoose.Types.ObjectId; text: string; createdAt: Date }[];
  isOpenForClaim: boolean;
  contentItemId?: mongoose.Types.ObjectId;
  autoGenerated: boolean;
  generationGroup?: string;
  createdAt: Date;
  updatedAt: Date;
}

const ChecklistItemSchema = new Schema({ text: String, done: { type: Boolean, default: false } }, { _id: true });
const AttachmentSchema = new Schema({ name: String, url: String, type: String }, { _id: true });
const CommentSchema = new Schema(
  { userId: { type: Schema.Types.ObjectId, ref: 'User' }, text: String, createdAt: { type: Date, default: Date.now } },
  { _id: true }
);

const TaskSchema = new Schema<ITaskDoc>(
  {
    boardId: { type: Schema.Types.ObjectId, ref: 'Board', required: true },
    clientId: { type: Schema.Types.ObjectId, ref: 'Client', required: true },
    title: { type: String, required: true },
    description: { type: String },
    taskType: {
      type: String,
      enum: ['PHOTOSHOOT', 'VIDEO_SHOOT', 'DRONE', 'EDITING', 'REEL', 'STORY', 'POST_DESIGN', 'COPYWRITING', 'CLIENT_APPROVAL', 'POSTING', 'REPORTING', 'PAYMENT', 'MEETING', 'OTHER'],
      default: 'OTHER',
    },
    status: {
      type: String,
      enum: ['TO_DO', 'IN_PROGRESS', 'WAITING_APPROVAL', 'APPROVED', 'SCHEDULED', 'POSTED', 'DONE', 'CANCELLED'],
      default: 'TO_DO',
    },
    priority: { type: String, enum: ['LOW', 'MEDIUM', 'HIGH', 'URGENT'], default: 'MEDIUM' },
    assignedTo: { type: Schema.Types.ObjectId, ref: 'User' },
    claimedBy: { type: Schema.Types.ObjectId, ref: 'User' },
    createdBy: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    deadline: { type: Date },
    startDate: { type: Date },
    completedAt: { type: Date },
    platforms: [{ type: String }],
    checklist: [ChecklistItemSchema],
    attachments: [AttachmentSchema],
    comments: [CommentSchema],
    isOpenForClaim: { type: Boolean, default: false },
    contentItemId: { type: Schema.Types.ObjectId, ref: 'ContentItem' },
    autoGenerated: { type: Boolean, default: false },
    generationGroup: { type: String },
  },
  { timestamps: true }
);

const Task: Model<ITaskDoc> = mongoose.models.Task ?? mongoose.model<ITaskDoc>('Task', TaskSchema);
export default Task;
