import mongoose, { Schema, Document, Model } from 'mongoose';

export type ReportStatus = 'NOT_POSTED' | 'WAITING_FOR_REPORT_TIME' | 'NEEDS_REPORT_DATA' | 'COMPLETED';

export interface IMetrics {
  views?: number;
  reach?: number;
  likes?: number;
  comments?: number;
  shares?: number;
  saves?: number;
  profileVisits?: number;
  linkClicks?: number;
  storyReplies?: number;
  storyTapsForward?: number;
  storyTapsBack?: number;
  storyExits?: number;
  engagementRate?: number;
  notes?: string;
  screenshotUrl?: string;
}

export interface IReporting {
  reportDueAt?: Date;
  reportStatus: ReportStatus;
  reportCompletedAt?: Date;
  metrics?: IMetrics;
}

export interface ITaskDoc extends Document {
  boardId: mongoose.Types.ObjectId;
  clientId: mongoose.Types.ObjectId;
  title: string;
  description?: string;
  contentType: 'POST' | 'REEL' | 'STORY' | 'CAROUSEL' | 'VIDEO' | 'PHOTO' | 'OTHER';
  status: 'CONTENT_PREPARATION' | 'QUALITY_ASSURANCE' | 'POST_VERIFIED' | 'READY_TO_POST' | 'POSTED' | 'NEEDS_FIX';
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
  platforms?: string[];
  assignedTo?: mongoose.Types.ObjectId;
  claimedBy?: mongoose.Types.ObjectId;
  createdBy: mongoose.Types.ObjectId;
  deadline?: Date;
  scheduledDate?: Date;
  postedDate?: Date;
  checklist?: { text: string; done: boolean }[];
  links?: { label: string; url: string; type?: string }[];
  comments?: { userId: mongoose.Types.ObjectId; text: string; createdAt: Date }[];
  reporting?: IReporting;
  isOpenForClaim: boolean;
  autoGenerated: boolean;
  isDemo: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const ChecklistItemSchema = new Schema({ text: String, done: { type: Boolean, default: false } }, { _id: true });

const LinkSchema = new Schema({ label: String, url: String, type: { type: String, default: 'OTHER' } }, { _id: true });

const CommentSchema = new Schema(
  { userId: { type: Schema.Types.ObjectId, ref: 'User' }, text: String, createdAt: { type: Date, default: Date.now } },
  { _id: true }
);

const MetricsSchema = new Schema<IMetrics>(
  {
    views: { type: Number },
    reach: { type: Number },
    likes: { type: Number },
    comments: { type: Number },
    shares: { type: Number },
    saves: { type: Number },
    profileVisits: { type: Number },
    linkClicks: { type: Number },
    storyReplies: { type: Number },
    storyTapsForward: { type: Number },
    storyTapsBack: { type: Number },
    storyExits: { type: Number },
    engagementRate: { type: Number },
    notes: { type: String },
    screenshotUrl: { type: String },
  },
  { _id: false }
);

const ReportingSchema = new Schema<IReporting>(
  {
    reportDueAt: { type: Date },
    reportStatus: {
      type: String,
      enum: ['NOT_POSTED', 'WAITING_FOR_REPORT_TIME', 'NEEDS_REPORT_DATA', 'COMPLETED'],
      default: 'NOT_POSTED',
    },
    reportCompletedAt: { type: Date },
    metrics: { type: MetricsSchema },
  },
  { _id: false }
);

const TaskSchema = new Schema<ITaskDoc>(
  {
    boardId: { type: Schema.Types.ObjectId, ref: 'Board', required: true },
    clientId: { type: Schema.Types.ObjectId, ref: 'Client', required: true },
    title: { type: String, required: true },
    description: { type: String },
    contentType: {
      type: String,
      enum: ['POST', 'REEL', 'STORY', 'CAROUSEL', 'VIDEO', 'PHOTO', 'OTHER'],
      default: 'OTHER',
    },
    status: {
      type: String,
      enum: ['CONTENT_PREPARATION', 'QUALITY_ASSURANCE', 'POST_VERIFIED', 'READY_TO_POST', 'POSTED', 'NEEDS_FIX'],
      default: 'CONTENT_PREPARATION',
    },
    priority: { type: String, enum: ['LOW', 'MEDIUM', 'HIGH', 'URGENT'], default: 'MEDIUM' },
    platforms: [{ type: String }],
    assignedTo: { type: Schema.Types.ObjectId, ref: 'User' },
    claimedBy: { type: Schema.Types.ObjectId, ref: 'User' },
    createdBy: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    deadline: { type: Date },
    scheduledDate: { type: Date },
    postedDate: { type: Date },
    checklist: [ChecklistItemSchema],
    links: [LinkSchema],
    comments: [CommentSchema],
    reporting: { type: ReportingSchema, default: () => ({ reportStatus: 'NOT_POSTED' }) },
    isOpenForClaim: { type: Boolean, default: false },
    autoGenerated: { type: Boolean, default: false },
    isDemo: { type: Boolean, default: false },
  },
  { timestamps: true }
);

const Task: Model<ITaskDoc> = mongoose.models.Task ?? mongoose.model<ITaskDoc>('Task', TaskSchema);
export default Task;
